2019-06-10 14:52:31 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.setSavepoint(JdbcConnection.java:1064)
	at com.djrapitops.plan.db.access.transactions.Transaction.initializeTransaction(Transaction.java:108)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:65)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-10 14:52:32 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.setSavepoint(JdbcConnection.java:1064)
	at com.djrapitops.plan.db.access.transactions.Transaction.initializeTransaction(Transaction.java:108)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:65)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-25 09:37:41 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:347)
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:41)
	at com.djrapitops.plan.db.access.queries.LargeStoreQueries.lambda$storeAllSessionsWithKillAndWorldData$0(LargeStoreQueries.java:354)
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119)
	at com.djrapitops.plan.db.access.transactions.events.ServerShutdownTransaction.performOperations(ServerShutdownTransaction.java:40)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-25 09:37:41 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1557)
	at plan.org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1116)
	at com.djrapitops.plan.db.access.transactions.Transaction.manageFailure(Transaction.java:80)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:70)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-25 09:38:01 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.setSavepoint(JdbcConnection.java:1064)
	at com.djrapitops.plan.db.access.transactions.Transaction.initializeTransaction(Transaction.java:108)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:65)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-13 10:29:10 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.setSavepoint(JdbcConnection.java:1064)
	at com.djrapitops.plan.db.access.transactions.Transaction.initializeTransaction(Transaction.java:108)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:65)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-13 10:29:10 database: flush
plan.org.h2.message.DbException: (Message HY000 not found) [50000-199]
	at plan.org.h2.message.DbException.get(DbException.java:194)
	at plan.org.h2.message.DbException.convert(DbException.java:347)
	at plan.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at plan.org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at plan.org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at plan.org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at plan.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at plan.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at plan.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at plan.org.h2.engine.Database.getPageStore(Database.java:2739)
	at plan.org.h2.engine.Database.open(Database.java:769)
	at plan.org.h2.engine.Database.openDatabase(Database.java:319)
	at plan.org.h2.engine.Database.<init>(Database.java:313)
	at plan.org.h2.engine.Engine.openSession(Engine.java:69)
	at plan.org.h2.engine.Engine.openSession(Engine.java:201)
	at plan.org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at plan.org.h2.engine.Engine.createSession(Engine.java:161)
	at plan.org.h2.engine.Engine.createSession(Engine.java:31)
	at plan.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at plan.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at plan.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at plan.org.h2.Driver.connect(Driver.java:69)
	at plan.org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:189)
	at plan.org.h2.jdbcx.JdbcDataSource.getConnection(JdbcDataSource.java:160)
	at com.djrapitops.plan.db.H2DB.getConnectionFor(H2DB.java:99)
	at com.djrapitops.plan.db.H2DB.getNewConnection(H2DB.java:84)
	at com.djrapitops.plan.db.H2DB.setupDataSource(H2DB.java:73)
	at com.djrapitops.plan.db.SQLDB.init(SQLDB.java:102)
	at com.djrapitops.plan.ServerShutdownSave.saveActiveSessions(ServerShutdownSave.java:106)
	at com.djrapitops.plan.ServerShutdownSave.attemptSave(ServerShutdownSave.java:92)
	at com.djrapitops.plan.ServerShutdownSave.performSave(ServerShutdownSave.java:84)
	at com.djrapitops.plan.Plan.onDisable(Plan.java:108)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377)
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437)
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:429)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:395)
	at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:679)
	at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:681)
	at net.minecraft.server.v1_14_R1.MinecraftServer.close(MinecraftServer.java:656)
	at org.bukkit.craftbukkit.v1_14_R1.util.ServerShutdownThread.run(ServerShutdownThread.java:16)
Caused by: plan.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 41 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/smtpserver/Minecraft/mcv/plugins/Plan/h2database.mv.db [1.4.199/7]
	at plan.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at plan.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at plan.org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 35 more
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
	at plan.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at plan.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 36 more
2019-07-14 11:20:55 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.setSavepoint(JdbcConnection.java:1064)
	at com.djrapitops.plan.db.access.transactions.Transaction.initializeTransaction(Transaction.java:108)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:65)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-14 11:20:55 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.setSavepoint(JdbcConnection.java:1064)
	at com.djrapitops.plan.db.access.transactions.Transaction.initializeTransaction(Transaction.java:108)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:65)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-16 16:40:53 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90030 not found); SQL statement:
INSERT INTO plan_sessions (uuid, session_start, session_end, deaths, mob_kills, afk_time, server_uuid) VALUES (?, ?, ?, ?, ?, ?, ?) [90030-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:194)
	at plan.org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:205)
	at plan.org.h2.mvstore.db.MVTable.convertException(MVTable.java:725)
	at plan.org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:202)
	at plan.org.h2.mvstore.db.MVTable.addRow(MVTable.java:546)
	at plan.org.h2.command.dml.Insert.insertRows(Insert.java:180)
	at plan.org.h2.command.dml.Insert.update(Insert.java:132)
	at plan.org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at plan.org.h2.command.Command.executeUpdate(Command.java:267)
	at plan.org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at plan.org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1280)
	at com.djrapitops.plan.db.access.ExecBatchStatement.callExecute(ExecBatchStatement.java:35)
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:52)
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:42)
	at com.djrapitops.plan.db.access.queries.LargeStoreQueries.lambda$storeAllSessionsWithKillAndWorldData$0(LargeStoreQueries.java:354)
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119)
	at com.djrapitops.plan.db.access.transactions.events.ServerShutdownTransaction.performOperations(ServerShutdownTransaction.java:40)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Transaction 1 has status CLOSED, not OPEN [1.4.199/103]
	at plan.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at plan.org.h2.mvstore.tx.Transaction.checkOpen(Transaction.java:487)
	at plan.org.h2.mvstore.tx.Transaction.log(Transaction.java:305)
	at plan.org.h2.mvstore.tx.TxDecisionMaker.logIt(TxDecisionMaker.java:131)
	at plan.org.h2.mvstore.tx.TxDecisionMaker.decide(TxDecisionMaker.java:69)
	at plan.org.h2.mvstore.tx.TxDecisionMaker$PutDecisionMaker.decide(TxDecisionMaker.java:199)
	at plan.org.h2.mvstore.MVMap.operate(MVMap.java:1670)
	at plan.org.h2.mvstore.tx.TransactionMap.set(TransactionMap.java:306)
	at plan.org.h2.mvstore.tx.TransactionMap.set(TransactionMap.java:289)
	at plan.org.h2.mvstore.tx.TransactionMap.put(TransactionMap.java:226)
	at plan.org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:200)
	... 19 more
2019-07-16 16:40:53 jdbc[3]: exception
plan.org.h2.jdbc.JdbcBatchUpdateException: (Message 90030 not found); SQL statement:
INSERT INTO plan_sessions (uuid, session_start, session_end, deaths, mob_kills, afk_time, server_uuid) VALUES (?, ?, ?, ?, ?, ?, ?) [90030-199]
	at plan.org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1298)
	at com.djrapitops.plan.db.access.ExecBatchStatement.callExecute(ExecBatchStatement.java:35)
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:52)
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:42)
	at com.djrapitops.plan.db.access.queries.LargeStoreQueries.lambda$storeAllSessionsWithKillAndWorldData$0(LargeStoreQueries.java:354)
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119)
	at com.djrapitops.plan.db.access.transactions.events.ServerShutdownTransaction.performOperations(ServerShutdownTransaction.java:40)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90030 not found); SQL statement:
INSERT INTO plan_sessions (uuid, session_start, session_end, deaths, mob_kills, afk_time, server_uuid) VALUES (?, ?, ?, ?, ?, ?, ?) [90030-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:194)
	at plan.org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:205)
	at plan.org.h2.mvstore.db.MVTable.convertException(MVTable.java:725)
	at plan.org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:202)
	at plan.org.h2.mvstore.db.MVTable.addRow(MVTable.java:546)
	at plan.org.h2.command.dml.Insert.insertRows(Insert.java:180)
	at plan.org.h2.command.dml.Insert.update(Insert.java:132)
	at plan.org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at plan.org.h2.command.Command.executeUpdate(Command.java:267)
	at plan.org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at plan.org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1280)
	at com.djrapitops.plan.db.access.ExecBatchStatement.callExecute(ExecBatchStatement.java:35)
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:52)
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:42)
	at com.djrapitops.plan.db.access.queries.LargeStoreQueries.lambda$storeAllSessionsWithKillAndWorldData$0(LargeStoreQueries.java:354)
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119)
	at com.djrapitops.plan.db.access.transactions.events.ServerShutdownTransaction.performOperations(ServerShutdownTransaction.java:40)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Transaction 1 has status CLOSED, not OPEN [1.4.199/103]
	at plan.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at plan.org.h2.mvstore.tx.Transaction.checkOpen(Transaction.java:487)
	at plan.org.h2.mvstore.tx.Transaction.log(Transaction.java:305)
	at plan.org.h2.mvstore.tx.TxDecisionMaker.logIt(TxDecisionMaker.java:131)
	at plan.org.h2.mvstore.tx.TxDecisionMaker.decide(TxDecisionMaker.java:69)
	at plan.org.h2.mvstore.tx.TxDecisionMaker$PutDecisionMaker.decide(TxDecisionMaker.java:199)
	at plan.org.h2.mvstore.MVMap.operate(MVMap.java:1670)
	at plan.org.h2.mvstore.tx.TransactionMap.set(TransactionMap.java:306)
	at plan.org.h2.mvstore.tx.TransactionMap.set(TransactionMap.java:289)
	at plan.org.h2.mvstore.tx.TransactionMap.put(TransactionMap.java:226)
	at plan.org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:200)
	... 19 more
2019-07-16 16:40:53 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1557)
	at plan.org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1116)
	at com.djrapitops.plan.db.access.transactions.Transaction.manageFailure(Transaction.java:80)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:70)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-16 16:41:13 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientException: (Message 90007 not found) [90007-199]
2019-07-16 17:04:59 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.setSavepoint(JdbcConnection.java:1064)
	at com.djrapitops.plan.db.access.transactions.Transaction.initializeTransaction(Transaction.java:108)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:65)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-16 17:04:59 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.setSavepoint(JdbcConnection.java:1064)
	at com.djrapitops.plan.db.access.transactions.Transaction.initializeTransaction(Transaction.java:108)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:65)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-16 21:14:11 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:347)
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:41)
	at com.djrapitops.plan.db.access.queries.LargeStoreQueries.lambda$storeAllSessionsWithKillAndWorldData$0(LargeStoreQueries.java:354)
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119)
	at com.djrapitops.plan.db.access.transactions.events.ServerShutdownTransaction.performOperations(ServerShutdownTransaction.java:40)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-16 21:14:11 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1557)
	at plan.org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1116)
	at com.djrapitops.plan.db.access.transactions.Transaction.manageFailure(Transaction.java:80)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:70)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-16 21:14:31 jdbc[3]: exception
plan.org.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90121 not found) [90121-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at plan.org.h2.message.DbException.get(DbException.java:205)
	at plan.org.h2.message.DbException.get(DbException.java:181)
	at plan.org.h2.message.DbException.get(DbException.java:170)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at plan.org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at plan.org.h2.jdbc.JdbcConnection.setSavepoint(JdbcConnection.java:1064)
	at com.djrapitops.plan.db.access.transactions.Transaction.initializeTransaction(Transaction.java:108)
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:65)
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
